export default {
    name: 'en',
    keys: {
        dialogs : "dialogs",
        groupchats : "groupchats",
        newGroupchat : "new groupchat",
        signIn : "sign in",
        signUp : "sign up",
        signOut : "sign out",
        ok : "ok",
        email : "email",
        password : "password",
        passwordAgain : "password again",
        name : "name",
        surname : "surname",
        uploadPicture : "upload picture",
        menu : "menu",
        remove : "remove",
        add : "add",
        cancel : "cancel",
        all : "all",
        friends : "friends",
        requests : "requests",
        search : "search",
        home : "home",
        chats : "chats",
        chatName : "chat name",
        startDialog : 'start dialog...',
        settings : 'settings',
        send : 'send',
        yourMessage : 'your message...',
        accept : 'accept',
        decline : 'decline'
    }
}