export default {
    name: 'ru',
    keys: {
        dialogs : "диалоги",
        groupchats : "групчаты",
        newGroupchat : "новый групчат",
        signIn : "вход",
        signUp : "регистрация",
        signOut : "выйти",
        ok : "готово",
        email : "почта",
        password : "пароль",
        passwordAgain : "пароль вновь",
        name : "имя",
        surname : "фамилия",
        uploadPicture : "загрузить фотографию",
        menu : "меню",
        remove : "удалить",
        add : "добавить",
        cancel : "отменить",
        all : "все",
        friends : "друзья",
        requests : "заявки",
        search : "поиск",
        home : "главная",
        chats : "чаты",
        chatName : "название чата",
        startDialog : 'начать диалог...',
        settings : 'настройки',
        send : 'отправить',
        yourMessage : 'твоё сообщение...',
        accept : 'принять',
        decline : 'отклонить'
    }
}